"""Create orders table and relation

Revision ID: 209688e05724
Revises: b7956b0c048d
Create Date: 2020-05-12 12:13:15.216977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209688e05724'
down_revision = 'b7956b0c048d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
